FROM nginx
COPY conf/nginx.conf /etc/nginx/nginx.conf
RUN rm -rf /etc/nginx/conf.d/*; exit 0
COPY conf/nginx.conf /etc/nginx/nginx.conf
COPY conf/api/* /etc/nginx/conf.d
RUN apt-get update && apt-get install -y curl

EXPOSE 80