version: '2.1'
services:
  authentication:
    build: 
      context: ./authentication
      dockerfile: DockerFile
    environment:
      SERVICE_NAME: authentication
  notifications:
    build: 
      context: ./notifications
      dockerfile: DockerFile
    environment:
      SERVICE_NAME: notifications
  transactions:
    build: 
      context: ./transactions
      dockerfile: DockerFile
    environment:
      SERVICE_NAME: transactions
  users:
    build: 
      context: ./users    
      dockerfile: DockerFile
    environment:
      SERVICE_NAME: users
    ports:
    - 80

  gateway:
    build: 
      context: ./api-gateway  
      dockerfile: DockerFile    
    links:
      - authentication
      - notifications
      - transactions
      - users
    ports:
      - "80:80"
    
