version: '2.1'

  authentication:
    build: 
      context: ./authentication
      dockerfile: Dockerfile-alternate
    environment:
      SERVICE_NAME: authentication
  notifications:
    build: 
      context: ./notifications
      dockerfile: Dockerfile-alternate
    environment:
      SERVICE_NAME: notifications
  transactions:
    build: 
      context: ./transactions
      dockerfile: Dockerfile-alternate
    environment:
      SERVICE_NAME: transactions
  users:
    build: 
      context: ./users    
      dockerfile: Dockerfile-alternate
    environment:
      SERVICE_NAME: users

  gateway:
    build: 
      context: ./api-gateway  
      dockerfile: Dockerfile-alternate    
    links:
      - authentication
      - notifications
      - transactions
      - users
    ports:
      - 80
