
authentication:
  build: authentication
  environment:
    SERVICE_NAME: authentication
notifications:
  build: notifications
  environment:
    SERVICE_NAME: notifications
transactions:
  build: transactions
  environment:
    SERVICE_NAME: transactions
users:
  build: users
  environment:
    SERVICE_NAME: users

gateway:
  build: api-gateway
  links:
    - authentication
    - notifications
    - transactions
    - users
  ports:
    - 80
